name: Build on Ubuntu Latest

on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.3'
          host: 'linux'
          target: 'desktop'
          install-deps: 'true'
          archives: 'qtmultimedia qtqml qtqmlcore qtqmlmodels qtwidgets qtquick qtquickcontrols qtopengl qtcore qtbase qtdeclarative qtsvg qtcmake qtconcurrent qtgui'
          modules: 'qtmultimedia'
          setup-python: 'true'
          set-env: 'true'
          tools-only: 'false'
      - name: Install required libs
        run: |
          sudo apt install ninja-build cmake build-essential libgl1-mesa-dev libicu-dev
          sudo apt-get install libicu-dev=56
      - name: build 
        run: cmake .; make
